config/routes.rb
Rails.application.routes.draw do

  root                  'static_pages#home'

  resources :events
  
  get 'users'      =>   'users#index'

  get 'users/show'

  get 'new_users'   =>  'users#new'

  get 'users/delete'

  get 'user_edit'   =>  'users#edit'

  post 'users/create'

  get 'users/create'

  post 'users/update'

  post 'users/destroy'

  get 'c_events_users' => 'events#c_events_users'

  get 'about'       =>  'static_pages#about'

  get 'events'      =>  'events#index'

  get 'calendar'    =>  'static_pages#calendar'

  get 'contacts'     =>  'contacts#new'

  get 'events_cal'  =>  'events#calendar_events'


  get 'groups'        =>  'groups#index'

  get 'groups/show'

  get 'groups/new'

  get 'groups/edit'

  get 'groups/delete'

  post 'groups/create'

  post 'groups/update'

  post 'groups/destroy'

  post 'contacts/create' => 'contacts#create'

  get 'comments'    =>  'faqcomments#index'

  get 'admin'       => 'admin#index'

  get 'logout'      => 'application#logout'

end

app/models/event.rb
class Event < ActiveRecord::Base

  has_and_belongs_to_many :groups
  has_and_belongs_to_many :users
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates :name, presence: true

  scope :sorted, lambda { order("events.name ASC")}

  scope :type_sort, lambda { order("events.type ASC")}

  scope :time_sort, lambda { order("events.time DESC")}

  scope :type, lambda { |query|
    where(["type LIKE ?", "%#{query}%"])
  }

  scope :search, lambda { |query|
    where(["name LIKE ?", "%#{query}%"])
  }

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.time_sort
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
    @time = Time.at(params[:time].to_i/1000) if params[:time]
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      flash[:notice] = "Event created successfully!"
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update_attributes(event_params)
      flash[:notice] = "Event updated successfully!"
      redirect_to(:action => 'show', :id => @event.id)
    else
      render('edit')
    end
  end

  def calendar_events
    @events = Event.all
    cal = []
    @events.each do |event|
      cal << {
        id: event.id,
        title: event.name,
        description: event.details || '',
        start: event.time.iso8601
      }
    end
    render json: cal.to_json
  end

  def delete
    @group = Event.find(params[:id])
  end

  def destroy
    event = Event.find(params[:id]).destroy
    flash[:notice] = "The event '#{event.name}' was deleted successfully!"
    redirect_to(:action => 'index')
  end

  def c_events_users                                                            # This method prevents users from joining events twice
    event = Event.find(params[:id])
    if event.users.include? current_user
      flash[:notice] = "You already joined the event!"
      redirect_to(:action => 'index')
    else
      event.users << current_user
      event.save
      flash[:notice] = "You successfully joined the event!"
      redirect_to(:action => 'show', :id => event.id)
    end
  end

  private

    def event_params
      params.require(:event).permit(:name, :venue, :time, :category, :capacity, :phone_number, :details)
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/delete.html.erb
<%= link_to("Back to list", { :action => 'index'}, :class => 'back-link') %>

<div class="events delete">
  <h2> Delete Event</h2>

  <%= form_for(:event, :url => { :action => 'destroy', :id => @event.id }) do |f| %>
    <p>Are you sure you want to permanently delete this event?</p>

    <p class="reference-name"><%= @event.id %> <%= @event.event_name %></p>

    <div class="form-buttons">
      <%= submit_tag("Delete Event") %>
    </div>

  <% end %>

</div>

app/views/events/edit.html.erb
<div class="events edit">
  <h2>Edit Event</h2>
  <%= link_to("<< Back to List",{ :action => 'index' }, :class => 'back-link btn btn-default') %><hr>

  <div class="row">
    <div class="col-xs-offset-1 col-xs-9">
      <%= form_for @event, :html => { :multipart => true } do |f| %>
          <div class="form-group">
            <label for="name">Event Name</label>
            <%= f.text_field(:name, class: 'form-control') %>
          </div>

          <div class="form-group">
            <label for="venue">Venue</label>
            <%= f.text_field(:venue, class: 'form-control') %>
          </div>

          <div class="form-group">
            <label for="time">Time</label>
            <%= f.datetime_select(:time, default: @time) %>
          </div>

          <div class="form-group">
            <label for="type">Type</label>
            <%= f.select :category, ["Select Type", "meeting", "conference", "party", "camping trip", "other"] %>
          </div>

          <div class="form-group">
            <label for="capacity">Capacity</label>
            <%= f.text_field(:capacity, class: 'form-control') %>
          </div>

          <div class="form-group">
            <label for="number">Phone Number</label>
            <%= f.text_field(:phone_number, class: 'form-control', id:'file_field') %>
          </div>

          <div class="form-group">
            <label for="pic">Pic</label>
            <%= f.file_field(:avatar, class: 'form-control btn btn-default') %>
          </div>
          <hr>
          <div class="form-group">
            <label for="details">Details</label>
            <%= f.text_area(:details, size: '15x15',class: 'form-control') %>
          </div>


          <div class="form-buttons">
            <%= submit_tag("Update", class: 'btn btn-default') %>
          </div>

          <%= params[:some_param] %>

      <% end %>
    </div>
  </div>

</div>

app/views/events/index.html.erb
<% @header="Events" %>
<div class="events index">

  <%= link_to 'Create New Event', new_event_path, :class => 'action new btn btn-default' %><hr>

  <div class="row">
    <div class="[ col-xs-12 col-sm-offset-1 col-sm-10 ]">
      <ul class="event-list">
        <% @events.each do |event| %>
        <li>
          <time datetime="2014-07-20 2000">
            <span class="day"><%= event.time.to_s(:day) %></span>
            <span class="month"><%= event.time.to_s(:month) %></span>
            <span class="year"><%= event.time.to_s(:year) %></span>
            <span class="time"><%= event.time.to_s(:time) %></span>
          </time>
          <%= image_tag('pic1.JPG') %>
          <div class="info">
            <h2 class="title"><%= link_to(event.name, event_path(event), :class =>'title') %></h2>
            <p class="desc"><%= event.details %></p>
            <ul>
              <li style="width:33%;"><%= link_to("JOIN", { :action => 'c_events_users', :id => event.id }, :class =>'title') %></li>
              <li style="width:34%;"><%= event.users.length %><span class="fa fa-male"></span></li>
            </ul>
          </div>
          <div class="social">
            <ul>
              <li class="facebook" style="width:33%;"><a href="#facebook"><span class="fa fa-facebook"></span></a></li>
              <li class="twitter" style="width:34%;"><a href="#twitter"><span class="fa fa-twitter"></span></a></li>
              <li class="google-plus" style="width:33%;"><a href="#google-plus"><span class="fa fa-google-plus"></span></a></li>
            </ul>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="events new">
  <h2>Events</h2>

  <%= link_to("Back to List", { :action => 'index' }, :class => 'back-link  btn btn-default') %>

  <div class="row">
    <div class="col-xs-offset-1 col-xs-9">
      <%= form_for @event do |f| %>
          <div class="form-group">
            <label for="name">Event Name</label>
            <%= f.text_field(:name, class: 'form-control') %>
          </div>

          <div class="form-group">
            <label for="venue">Venue</label>
            <%= f.text_field(:venue, class: 'form-control') %>
          </div>

          <div class="form-group">
            <label for="time">Time</label>
            <%= f.datetime_select(:time, default: @time) %>
          </div>

          <div class="form-group">
            <label for="type">Type</label>
            <%= f.select :category, ["Select Type", "meeting", "conference", "party", "camping trip", "other"]%>
          </div>

          <div class="form-group">
            <label for="capacity">Capacity</label>
            <%= f.text_field(:capacity, class: 'form-control') %>
          </div>

          <div class="form-group">
            <label for="number">Phone Number</label>
            <%= f.text_field(:phone_number, class: 'form-control') %>
          </div>

          <div class="form-group">
            <label for="details">Details</label>
            <%= f.text_area(:details, size: '15x15',class: 'form-control') %>
          </div>


          <div class="form-buttons">
            <%= submit_tag("Create Event", class: 'btn btn-default') %>
          </div>

          <%= params[:some_param] %>

      <% end %>
    </div>
  </div>

</div>

app/views/events/show.html.erb
<section class="main-body events show">
  <div class="container">
      <div class="fb-profile">
          <%= image_tag("pic6.jpg", size: '900x400', class: "fb-image-lg", align:"left", alt:"Event image") %>
          <div class="fb-profile-text">
              <h1><%= @event.name %></h1>
              <p></p>
          </div>
      </div>
  </div>
  <%= link_to("Back to list", { :action => 'index' }, :class => 'back-link btn btn-default pull-right') %><hr>
  <div class="event detail view">
    <div class="row">
      <div class="col-xs-3">
        <ul class="list-group">
          <li class="list-group-item text-muted" contenteditable="false">Event</li>
          <li class="list-group-item text-right"><span class="pull-left"><strong class="">Created On</strong></span><%= @event.created_at.to_formatted_s(:long_ordinal) %></li>
          <li class="list-group-item text-right"><span class="pull-left"><strong class="">Last Join</strong></span><%= @event.users.last.created_at.to_formatted_s(:long_ordinal) %></li>
          <li class="list-group-item text-right"><span class="pull-left"><strong class="">Created by</strong></span><%= @event.users.first.username %></li>
        </ul>
      </div>
      <div class="col-xs-8 min-main">
        <div class="row">
          <div class="col-xs-12 pads">
            Time: <%= @event.time.to_formatted_s(:long_ordinal) %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 pads">
            <%= @event.details %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>