config/routes.rb
Rails.application.routes.draw do

  root                  'static_pages#home'

  resources :events
  
  get 'users'      =>   'users#index'

  get 'users/show'

  get 'new_users'   =>  'users#new'

  get 'users/delete'

  get 'user_edit'   =>  'users#edit'

  post 'users/create'

  get 'users/create'

  post 'users/update'

  post 'users/destroy'

  get 'c_events_users' => 'events#c_events_users'

  get 'about'       =>  'static_pages#about'

  get 'events'      =>  'events#index'

  get 'calendar'    =>  'static_pages#calendar'

  get 'contacts'     =>  'contacts#new'

  get 'events_cal'  =>  'events#calendar_events'


  get 'groups'        =>  'groups#index'

  get 'groups/show'

  get 'groups/new'

  get 'groups/edit'

  get 'groups/delete'

  post 'groups/create'

  post 'groups/update'

  post 'groups/destroy'

  post 'contacts/create' => 'contacts#create'

  get 'comments'    =>  'faqcomments#index'

  get 'admin'       => 'admin#index'

  get 'logout'      => 'application#logout'

end

app/views/layouts/_event_carousel.html.erb
<div id="event_carousel" class="carousel slide" data-ride="carousel">

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("pic1.JPG") %>
    </div>

    <div class="item">
      <%= image_tag("pic1.JPG") %>
    </div>

    <div class="item">
      <%= image_tag("pic2.jpg") %>
    </div>

    <div class="item">
      <%= image_tag("pic3.JPG") %>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#event_carousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#event_carousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-lg-offset-3">
					<p class="copyright">Copyright &copy; 2015 - Edwin Agbenyega</p>
			</div>
		</div>
	</div>
	</div>

app/views/layouts/_header.html.erb
<header class="container-fluid text-center sm_header">
  <h1><%= @header if @header!="Home" %></h1>
</header>

app/views/layouts/_nav.html.erb
<!--Navigation Bar-->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">

    <!--Navbar's collapsable toggle button for smaller devices-->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Social Event Planner", root_path, class: "navbar-brand", id: "logo_name" %>
    </div>

    <!--Navbar's list-->
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><%= link_to "About",    about_path %></li>              <!--About-->
        <li><%= link_to "Events",   events_path %></li>             <!--Events-->
        <li><%= link_to "Groups",   groups_path %></li>             <!--Student Groups-->
        <li><%= link_to "Calendar",   calendar_path %></li>         <!--Calendar-->
        <li><%= link_to "Contacts", contacts_path %></li>            <!--Contacts-->
        <li><%= link_to "Sign out", logout_path %></li>
      </ul>
      <!--signup and login glyphicons on right of navbar-->
      <ul class="nav navbar-nav navbar-right">
         <li class="dropdown" id="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user pull-right"></span></a>
           <ul class="dropdown-menu">
             <li><%= link_to users_path do %>Profile<span class="glyphicon glyphicon-user pull-right"></span><% end %></li>
             <li class="divider"></li>
             <li><%= link_to raw('Edit Profile<span class="glyphicon glyphicon-user pull-right"></span>'), '#' %></li>
             <li class="divider"></li>
             <li><%= link_to raw('Admin<span class="glyphicon glyphicon-user pull-right"></span>'), admin_path %></li>
             <li class="divider"></li>
             <li><%= link_to raw('Sign Out<span class="glyphicon glyphicon-log-out pull-right"></span>'), logout_path %></li>
           </ul>
         </li>
       </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Unmsocial | <%= @header %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "application-print", :media => "print" %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= render 'layouts/shim' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if @header!= "Home" %>
  <div class="row">
  <%= render 'layouts/nav' %>
    <div class="col-md-offset-2 col-md-8 main-body">
      <% if @header %>
      <%= render 'layouts/header' %>
      <% end %>
  <% end %>
      <% if !flash[:notice].blank? %>
        <div class="notice">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>

</body>
</html>